"""company_members_cascade_on_delete

Revision ID: 00006
Revises: 00005
Create Date: 2025-11-11 12:43:11.901554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00006'
down_revision: Union[str, None] = '00005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'company_office')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_office', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
