"""add_cascade_delete_to_company_members

Revision ID: 00005
Revises: 00004
Create Date: 2025-11-11 12:41:34.010525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00005'
down_revision: Union[str, None] = '00004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_office', sa.String(length=15), nullable=True))
    op.drop_constraint(op.f('company_members_company_id_fkey'), 'company_members', type_='foreignkey')
    op.create_foreign_key(None, 'company_members', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_members', type_='foreignkey')
    op.create_foreign_key(op.f('company_members_company_id_fkey'), 'company_members', 'companies', ['company_id'], ['id'])
    op.drop_column('companies', 'company_office')
    # ### end Alembic commands ###
