"""introduce_membership_request_model

Revision ID: 00008
Revises: 00007
Create Date: 2025-11-19 22:16:18.877235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00008'
down_revision: Union[str, None] = '00007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_invitations', sa.Column('invitation_type', sa.Enum('COMPANY_INVITE', 'USER_REQUEST', name='invitationtype', native_enum=False), nullable=False))
    op.add_column('company_invitations', sa.Column('message', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_invitations', 'message')
    op.drop_column('company_invitations', 'invitation_type')
    # ### end Alembic commands ###
